<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">{ Slim3 View Example }</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <?php
                foreach ($nav as $link) {
                    if ($currentURL === $link['url']) {
                        $link['class'] = 'active';
                    }

                    echo '<li class="' . $link['class'] . '"><a href="' . $link['url'] . '">' .
                        '<i class="' . $link['icon'] . '"></i> ' . $link['label'] . '</a></li>';
                }
                ?>
            </ul>
        </div>
    </div>
</nav>
<?php if ($showTitle): ?>
    <header class="clearfix container">
        <h3 class="page-heading"><?php echo $pageTitle ?></h3>
    </header>
<?php endif; ?>
</div>
