<!--[home page template]-->
<p>Welcome to the example</p>

<p>This example app has a very simple structure as shown below</p>

<div class="panel panel-info">
    <div class="panel-heading">
        Folder Structure
    </div>
    <div class="panel-body">
        <pre>
app
├── app.php
└── themes
    └── default
        ├── layouts
        │   └── default.phtml
        └── views
            ├── pages
            │   ├── about.phtml
            │   └── homepage.phtml
            └── shared
                ├── header.phtml
                └── nav.phtml
        </pre>
    </div>
</div>
