<!--[home page template]-->
<p>Welcome to the example</p>

<p>This example app has a very simple structure as shown below</p>

<div class="panel panel-default">
    <div class="panel-heading">
        Folder Structure
    </div>
    <div class="panel-body">
        <pre>
app
├── app.php
├── config.json
└── themes
    ├── alternative
    │   ├── layouts
    │   │   └── page.phtml
    │   └── views
    │       └── pages
    │           └── about.phtml
    └── default
        ├── layouts
        │   └── default.phtml
        └── views
            ├── bits
            │   ├── header.phtml
            │   └── nav.phtml
            └── pages
                ├── about.phtml
                └── homepage.phtml
        </pre>
    </div>
</div>

<ul>
    <li>config.json provides the data to be set on the theme, including theme specific settings</li>
    <li>app.php shares all templates from default globally, so when `alternative` theme doesn't have a view template, it'll just borrow from default; when it does, it uses its own template.</li>
    <li>Click the navigation links to browse the alternative themes</li>
</ul>
