<!--[home page template]-->
<p>Welcome to the example (alternative theme)</p>

<p>You may notice this page is totally different to the homepage, as it's using an alternative theme.</p>

<p>Open <code>app.php</code> and you'll find out that it's simply calling
<pre>
    $theme->setTheme('alternative');
</pre>
in the router, and it's now using layout and views under <code>themes/alternative</code>
</p>

<p>Route code of the current page:</p>

<pre>
$pages['/alt'] = function ($request, $response, $args) use ($theme, $nav, $pages) {
    $theme->setTheme('alternative');
    $pages['/']($request, $response, $args);
};
</pre>
